# Generated by Django 4.2.1 on 2023-05-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakedByAl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery-images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
    ]
