# Generated by Django 4.2.1 on 2023-05-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BakedByAl', '0004_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('F', 'Fulfilled'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BakedByAl.galleryitem'),
        ),
    ]
