# Generated by Django 4.2.1 on 2023-05-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakedByAl', '0007_remove_order_order_items_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, default='no-image.png', upload_to='gallery-images/'),
        ),
    ]
